sudo: false
language: python
cache: pip
matrix:
    include:
        - python: 2.6
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - "pypy"
        # XXX - commented because OSX builds are deadly slow
        # - language: generic
        #   os: osx
        #   env: PYVER=py26
        - language: generic
          os: osx
          env: PYVER=py27
        # XXX - commented because OSX builds are deadly slow
        # - language: generic
        #   os: osx
        #   env: PYVER=py33
        - language: generic
          os: osx
          env: PYVER=py34
        # XXX - not supported yet
        # - language: generic
        #   os: osx
        #   env: PYVER=py35
install:
    - ./.ci/travis/install.sh
script:
    - ./.ci/travis/run.sh
after_success:
    - |
        if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] && [[ "$(uname -s)" != 'Darwin' ]]; then
            echo "sending test coverage results to coveralls.io"
            coveralls
        fi
