os: Visual Studio 2015

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_compiler.cmd"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.

    # 32 bits

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

    # 64 bits

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      ARCH: x86_64
      VS_VER: "2015"
      INSTANCENAME: "SQL2012SP1"

    # Also build on a Python version not pre-installed by Appveyor.
    # See: https://github.com/ogrisel/python-appveyor-demo/issues/10

    # - PYTHON: "C:\\Python266"
    #   PYTHON_VERSION: "2.6.6"
    #   PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell .ci\\appveyor\\install.ps1"
  # - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip install --upgrade --user setuptools pip"
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip --version"
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip install --upgrade --user unittest2 ipaddress pypiwin32 wmi wheel"
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip freeze"
  - "%WITH_COMPILER% %PYTHON%/python.exe setup.py build"
  - "%WITH_COMPILER% %PYTHON%/python.exe setup.py build build_ext -i"
  - "%WITH_COMPILER% %PYTHON%/python.exe setup.py develop"
  # 1.0.1 is the latest release supporting python 2.6
  - "%WITH_COMPILER% %PYTHON%/Scripts/pip.exe install mock==1.0.1"

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python -V"
  - "%WITH_COMPILER% %PYTHON%/python psutil/tests/runner.py"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wininst"

artifacts:
  - path: dist\*

# on_success:
#   - might want to upload the content of dist/*.whl to a public wheelhouse

skip_commits:
  message: skip-ci
