# Execute tests on *BSD platforms. Does not produce wheels.
# Useful URLs:
# https://github.com/vmactions/freebsd-vm
# https://github.com/vmactions/openbsd-vm
# https://github.com/vmactions/netbsd-vm

on: [push, pull_request]
name: bsd-tests
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.sha || '' }}
  cancel-in-progress: true
jobs:
  freebsd:
    # if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            make test-ci

  openbsd:
    # if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          run: |
            make test-ci

  netbsd:
    if: false  # XXX: disabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          run: |
            make test-ci
