# Executed every time an issue or PR is opened. Inspects the title string
# and sets the appropriate labels.
# See: https://github.com/Naturalclar/issue-action

name: "Set issue labels"
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          parameters: '[
  {"keywords": ["aix"], "labels": ["aix"], "assignees": ["wiggin15"]},
  {"keywords": ["cygwin"], "labels": ["cygwin"], "assignees": [""]},
  {"keywords": ["freebsd"], "labels": ["freebsd"], "assignees": [""]},
  {"keywords": ["linux", "ubuntu", "redhat", "red hat", "mint", "centos", "archlinux", "debian", "alpine", "gentoo", "fedora", "slackware", "suse", "opensuse", "manylinux", "apt", "rpm", "yum", "RHEL", "kali", "/sys/class", "/sys/block", "/proc/net", "/proc/disk", "/proc/smaps", "/proc/vmstat"], "labels": ["linux"], "assignees": [""]},
  {"keywords": ["macos", "mac ", "osx", "os x", "mojave", "sierra", "capitan", "darwin", "yosemite", "catalina", "xcode", "dylib"], "labels": ["macos"], "assignees": [""]},
  {"keywords": ["netbsd"], "labels": ["netbsd"], "assignees": [""]},
  {"keywords": ["openbsd"], "labels": ["openbsd"], "assignees": [""]},
  {"keywords": ["sunos", "solaris"], "labels": ["sunos"], "assignees": ["wiggin15"]},
  {"keywords": ["windows", "win32", "WinError", "WindowsError", "win10", "win7", "win", "mingw", "msys", "studio", "microsoft", "MSVC", "TCHAR", "WCHAR", "make.bat", ".bat", "appveyor", "handles", "CloseHandle", "GetLastError", "NtQuery", "OpenProcess", "TerminateProcess", "DLL", "System Idle Process"], "labels": ["windows"], "assignees": [""]},
  {"keywords": ["wsl"], "labels": ["wsl"], "assignees": [""]},
  {"keywords": ["enhancement"], "labels": ["enhancement"], "assignees": [""]},
  {"keywords": ["doc ", "document ", "documentation", "docfix", "readthedocs", "pythonhosted", "HISTORY", "README", "index.rst"], "labels": ["doc"], "assignees": [""]},
  {"keywords": ["idea", "proposal", "api", "feature"], "labels": ["api", "enhancement"], "assignees": [""]},
  {"keywords": ["performance", "speedup", "slow", "fast"], "labels": ["performance"], "assignees": [""]},
  {"keywords": ["pypy"], "labels": ["pypy"], "assignees": [""]},
  {"keywords": ["psposix", "_psutil_posix", "waitpid", "statvfs", "/dev/tty", "/dev/pts"], "labels": ["unix"], "assignees": [""]},
  {"keywords": ["memory leak", "leaks memory", "memleak", "mem leak"], "labels": ["memleak"], "assignees": [""]},
  {"keywords": ["example script", "examples script", "example dir", "scripts/"], "labels": ["scripts"], "assignees": [""]},
  {"keywords": ["test", "tests", "travis", "coverage", "travis", "cirrus", "appveyor", "continuous integration", "dev guide", "devguide", "sphinx", "unittest", "pytest"], "labels": ["tests"], "assignees": [""]},
  {"keywords": ["Makefile"], "labels": ["unix"], "assignees": [""]},
  {"keywords": ["segfault", "segmentation fault", "core dumped", "RuntimeError", "WinError", "WindowsError", "MemoryError", "OverflowError", "ZeroDivisionError", "SystemError", "MemoryError"], "labels": ["priority-high"], "assignees": [""]},
  {"keywords": ["fail", "can''t execute", "can''t install", "install error", "installation error", "crash", "critical"], "labels": ["bug"], "assignees": [""]},
  {"keywords": ["wheel"], "labels": ["wheels"], "assignees": [""]}
]'
